config/routes.rb
Rails.application.routes.draw do
  get 'home/help'
  get 'home/loan_applications'

  resources :loan_applications
  
  root to: 'home#index'

end

app/models/loan_application.rb
class LoanApplication < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def help
  end
  def loan_applications
  end
end

app/controllers/loan_applications_controller.rb
class LoanApplicationsController < ApplicationController
  before_action :set_loan_application, only: [:show, :edit, :update, :destroy]

  # GET /loan_applications
  # GET /loan_applications.json
  def index
    @loan_applications = LoanApplication.all
  end

  # GET /loan_applications/1
  # GET /loan_applications/1.json
  def show
  end

  # GET /loan_applications/new
  def new
    @loan_application = LoanApplication.new
  end

  # GET /loan_applications/1/edit
  def edit
  end

  # POST /loan_applications
  # POST /loan_applications.json
  def create
    @loan_application = LoanApplication.new(loan_application_params)

    respond_to do |format|
      if @loan_application.save
        format.html { redirect_to @loan_application, notice: 'Loan application was successfully created.' }
        format.json { render :show, status: :created, location: @loan_application }
      else
        format.html { render :new }
        format.json { render json: @loan_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loan_applications/1
  # PATCH/PUT /loan_applications/1.json
  def update
    respond_to do |format|
      if @loan_application.update(loan_application_params)
        format.html { redirect_to @loan_application, notice: 'Loan application was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan_application }
      else
        format.html { render :edit }
        format.json { render json: @loan_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loan_applications/1
  # DELETE /loan_applications/1.json
  def destroy
    @loan_application.destroy
    respond_to do |format|
      format.html { redirect_to loan_applications_url, notice: 'Loan application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan_application
      @loan_application = LoanApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_application_params
      params.require(:loan_application).permit(:personid, :loantype, :date, :loanamount, :comments)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loan_applications_helper.rb
module LoanApplicationsHelper
end

app/views/home/help.html.erb
<h1>Home#help</h1>
<p>Find me in app/views/home/help.html.erb</p>

app/views/home/index.html.erb
<h1>home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onepayapps</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Loans", loan_applications_path %></li>
      <li><%= link_to "Help", home_help_path %></li>
      <li><%= link_to "Login", root_path %></li>
    </ul>
  </div>
  
<%= yield %>

</body>
</html>

app/views/loan_applications/_form.html.erb
<%= form_for(@loan_application) do |f| %>
  <% if @loan_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan_application.errors.count, "error") %> prohibited this loan_application from being saved:</h2>

      <ul>
      <% @loan_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :personid %><br>
    <%= f.text_field :personid %>
  </div>
  <div class="field">
    <%= f.label :loantype %><br>
    <%= f.text_field :loantype %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :loanamount %><br>
    <%= f.text_field :loanamount %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loan_applications/edit.html.erb
<h1>Editing loan_application</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan_application %> |
<%= link_to 'Back', loan_applications_path %>

app/views/loan_applications/index.html.erb
<h1>Listing loan_applications</h1>

<table>
  <thead>
    <tr>
      <th>PersonID</th>
      <th>Loantype</th>
      <th>Date</th>
      <th>Loanamount</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loan_applications.each do |loan_application| %>
      <tr>
        <td><%= loan_application.personid %></td>
        <td><%= loan_application.loantype %></td>
        <td><%= loan_application.date %></td>
        <td><%= loan_application.loanamount %></td>
        <td><%= loan_application.comments %></td>
        <td><%= link_to 'Show', loan_application %></td>
        <td><%= link_to 'Edit', edit_loan_application_path(loan_application) %></td>
        <td><%= link_to 'Destroy', loan_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan application', new_loan_application_path %>

app/views/loan_applications/new.html.erb
<h1>New loan_application</h1>

<%= render 'form' %>

<%= link_to 'Back', loan_applications_path %>

app/views/loan_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>PersonId:</strong>
  <%= @loan_application.personid %>
</p>

<p>
  <strong>Loantype:</strong>
  <%= @loan_application.loantype %>
</p>

<p>
  <strong>Date:</strong>
  <%= @loan_application.date %>
</p>

<p>
  <strong>Loanamount:</strong>
  <%= @loan_application.loanamount %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @loan_application.comments %>
</p>

<%= link_to 'Edit', edit_loan_application_path(@loan_application) %> |
<%= link_to 'Back', loan_applications_path %>